In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.4 MB 33.1 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.4 MB 31.9 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 29.8 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy

In [4]:
import numpy as np

print(np.__version__)

2.4.3


In [5]:
alist = [1,2,3,4,5,6,7]

In [6]:
type(alist)

list

In [7]:
print(type(alist))

<class 'list'>


In [8]:
alist

[1, 2, 3, 4, 5, 6, 7]

In [9]:
ar1 = np.array(alist)

In [12]:
print(type(ar1))
print(ar1)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [13]:
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
ar1.dtype

dtype('int64')

In [17]:
list_data = [1,2.0,3]

ar2 = np.array(list_data)
print(ar2)
print(ar2.dtype)

[1. 2. 3.]
float64


In [18]:
ar1.ndim

1

In [ ]:
ar1.shape #(7) 몇행 몇열

(7,)

In [20]:
ar3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
print(ar3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
print(ar3.ndim)

2


In [23]:
print(ar3.shape)

(3, 4)


In [27]:
ar4 = ar3.reshape(2, -1)

In [28]:
print(ar4)
print(ar4.ndim)
print(ar4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)


In [32]:
ar3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
ar5 = ar3.reshape(3,2,2)

In [39]:
print(ar5)
print(ar5.ndim)
print(ar5.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


In [44]:
x = np.arange(1,6)
y = np.arange(6,11)

In [45]:
x+y

array([ 7,  9, 11, 13, 15])

In [46]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [47]:
print(x+1)
print(x-1)
print(x*2)
print(x/2)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [40]:
L = range(1000)
%timeit L2= [i**2 for i in L]

65.5 μs ± 9.88 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
arr = np.arange(1000)
%timeit arr2 = arr ** 2

1.49 μs ± 152 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [49]:
x == 1

array([ True, False, False, False, False])

In [50]:
a = [[0,1,2],[3,4,5]]

In [54]:
# 0, 1, 5 인덱싱으로 뽑아주세요

a[0][0], a[0][1], a[-1][-1]

(0, 1, 5)

In [55]:
b = np.array([[0,1,2],[3,4,5]])

In [56]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
print(b[0][0], b[0][1], b[-1][-1])

0 1 5


In [59]:
c = np.array([[0,1,2,3], [4,5,6,7]])
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
# [0,1,2] , [1,5] 뽑기

print(c[0, :3], c[:,1])
print(c[:,0:2])

[0 1 2] [1 5]
[[0 1]
 [4 5]]


In [71]:
a=np.array([1,2,3])
b=np.array([10,20,30])

2*a+b

array([12, 24, 36])

In [72]:
a==2

array([False,  True, False])

In [73]:
b>10

array([False,  True,  True])

In [74]:
(a==2)&(b>10)

array([False,  True, False])

In [77]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([False, False, True, False, True, False, True, False, True, False])
a[idx]

array([2, 4, 6, 8])

In [80]:
# 조건문 연산을 사용하여 짝수인 원소만 골라내기

a = np.array([0,1,2,3,4,5,6,7,8,9])

print(a % 2 == 0)
print(a[a % 2 == 0])

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [81]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [83]:
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33,
       33])

In [84]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
print(a[:,[0,3]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [107]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [111]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

# 배열에서 3의 배수 찾기
print(x[x % 3 == 0])

# 배열에서 4로 나누면 1이 남는 수
print(x[x % 4 == 1])

# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수
print(x[(x % 3 == 0)&(x % 4 ==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
